# Generated by Django 4.0.2 on 2022-02-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercomments',
            options={'verbose_name_plural': 'usercomments'},
        ),
    ]
