# Generated by Django 4.0.2 on 2022-03-19 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='end_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
