# Generated by Django 4.0.2 on 2022-03-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0002_upcomingevent_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevent',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
