# Generated by Django 4.0.2 on 2022-02-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0002_alter_usercomments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercomments',
            options={'verbose_name_plural': 'user comments'},
        ),
    ]
