# Generated by Django 4.0.2 on 2022-02-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0003_alter_usercomments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
