# Generated by Django 4.0.2 on 2022-02-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0004_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='booked_status',
            new_name='booked',
        ),
    ]
