# Generated by Django 3.1.5 on 2022-07-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0004_auto_20220722_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevent',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
