# Generated by Django 4.0.2 on 2022-02-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0005_rename_booked_status_player_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='picture',
            field=models.ImageField(blank=True, upload_to='player_image'),
        ),
    ]
