# Generated by Django 4.0.2 on 2022-02-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0006_player_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeragent',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
