# Generated by Django 4.0.2 on 2022-02-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0007_playeragent_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
