# Generated by Django 4.0.2 on 2022-02-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0008_alter_player_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('views', models.IntegerField(default=0)),
                ('blog', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to='blog_images')),
                ('date_published', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='playeragent',
            name='player',
        ),
        migrations.AddField(
            model_name='sport',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='PlayerAgent',
        ),
        migrations.AddField(
            model_name='sportblog',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsApp.sport'),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsApp.sportblog'),
        ),
        migrations.DeleteModel(
            name='SportsBlog',
        ),
    ]
