# Generated by Django 4.0.2 on 2022-02-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0011_alter_sportblog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportblog',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
