# Generated by Django 4.0.2 on 2022-02-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0012_sportblog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportblog',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
