# Generated by Django 4.0.2 on 2022-02-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0013_alter_sportblog_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
