# Generated by Django 4.0.2 on 2022-02-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0014_sport_likes_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportblog',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
