# Generated by Django 4.0.2 on 2022-02-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0017_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='likes',
        ),
    ]
