# Generated by Django 4.0.2 on 2022-02-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0018_remove_sport_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
