# Generated by Django 4.0.2 on 2022-02-23 17:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sportsApp', '0019_sport_likes_delete_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserComments',
            new_name='UserComment',
        ),
    ]
