# Generated by Django 4.0.2 on 2022-02-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0020_rename_usercomments_usercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpComingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('url', models.URLField(blank=True)),
                ('location', models.CharField(max_length=128)),
                ('summary', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='UpComingEvents',
        ),
    ]
